apiVersion: v1
kind: Secret
metadata:
  name: crawler-secrets
type: Opaque
stringData:
  DB_DSN: "host=db user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"
  DISCORD_BOT_TOKEN: <your_discord_bot_token>
